name: deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency: production_environment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: composer install --no-dev --no-interaction

      - name: Deploy
        uses: deployphp/action@v1
        with:
          private-key: ${{ secrets.PRIVATE_KEY }}
          known-hosts: ${{ secrets.KNOWN_HOSTS }}
          dep: deploy -o hostname=${{ vars.DEPLOY_HOST }} -o port=${{ vars.DEPLOY_PORT }} -o remote_user=${{ vars.DEPLOY_USER }} -o deploy_path=${{ vars.DEPLOY_PATH }}
