name: deploy

on:
  push:
    branches: [main]
  repository_dispatch:
  workflow_dispatch:

concurrency: production_environment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: composer install --no-dev --no-interaction

      - name: Deploy
        uses: deployphp/action@v1.0.23
        with:
          dep: deploy
          options:
            deploy_path: ${{ vars.DEPLOY_PATH }}
            hostname: ${{ vars.DEPLOY_HOST }}
            port: ${{ vars.DEPLOY_PORT }}
            remote_user: ${{ vars.DEPLOY_USER }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          known-hosts: ${{ secrets.KNOWN_HOSTS }}
