name: Deploy
run-name: >-
  ${{ format('[{0}] Deploy to [{4}@{2}:{3}]:{1}',
    github.event_name == 'workflow_dispatch' && 'manual'
      || github.event.action,
    inputs.deploy_path || vars.DEPLOY_PATH,
    inputs.deploy_host || vars.DEPLOY_HOST || 'kompasio.sk',
    inputs.deploy_port || vars.DEPLOY_PORT || '22',
    inputs.deploy_user || vars.DEPLOY_USER || 'root') }}
on:
  repository_dispatch:
    types:
    - site
  workflow_dispatch:
    inputs:
      deploy_path:
        description: Deploy path
      deploy_host:
        description: Deploy host
      deploy_port:
        description: Deploy port
      deploy_user:
        description: Deploy user
      known_hosts:
        description: Known hosts
permissions:
  contents: read
concurrency: >-
  ${{ inputs.deploy_path || vars.DEPLOY_PATH }}::${{
  inputs.deploy_host || vars.DEPLOY_HOST || 'kompasio.sk' }}::${{
  inputs.deploy_port || vars.DEPLOY_PORT || '22' }}::${{
  inputs.deploy_user || vars.DEPLOY_USER || 'root' }}
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Composer
        run: composer --no-interaction install --no-dev --optimize-autoloader
      - name: Deployer
        uses:
          deployphp/action@6242095e7207facf115ac4439760356bc52760ac # v1.0.23
        with:
          dep: >-
            deploy
            -o deploy_path=${{ inputs.deploy_path || vars.DEPLOY_PATH }}
            -o hostname=${{ inputs.deploy_host || vars.DEPLOY_HOST || 'kompasio.sk' }}
            -o port=${{ inputs.deploy_port || vars.DEPLOY_PORT || '22' }}
            -o remote_user=${{ inputs.deploy_user || vars.DEPLOY_USER || 'root' }}
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          known-hosts: ${{ inputs.known_hosts || vars.KNOWN_HOSTS }}
